// Deterministic canned agent outputs for dry-run mode. Keyed off the company
// name so repeated ticks are reproducible and the pipeline's failure branches
// get exercised: one lead audits clean (no_flaws), one needs a QA revision.

function hash(s: string): number {
  let h = 0
  for (const c of s) h = (h * 31 + c.charCodeAt(0)) | 0
  return Math.abs(h)
}

const FLAW_POOL = [
  { type: 'mobile', detail: 'Layout breaks below 480px; phone number renders off-screen', evidence: 'viewport meta missing; .header fixed at 960px', severity: 5 },
  { type: 'conversion', detail: 'No online booking or quote form — phone-only contact', evidence: 'no <form> elements found on any page', severity: 4 },
  { type: 'speed', detail: 'Hero image is a 4.2MB PNG; first paint over 6s on 4G', evidence: 'hero.png 4.2MB, no compression, no lazy loading', severity: 4 },
  { type: 'seo', detail: 'Homepage title is just the company name — invisible for "emergency plumber <city>" searches', evidence: '<title>Company Inc</title>, no meta description', severity: 3 },
  { type: 'trust', detail: 'Copyright footer says 2019; latest review shown is 3 years old', evidence: 'footer text "© 2019"; testimonial dates', severity: 3 },
  { type: 'layout', detail: 'Services page returns 404 from the main nav', evidence: 'nav link /services -> HTTP 404', severity: 4 },
]

// Realistic per-gap skill bodies. In claude-code/api mode, runAgent bypasses
// this entirely and a real model writes the file from the same gap context.
const DEV_AGENT_TEMPLATES: Record<string, string> = {
  draft_prescreen: `import { BaseSkill, SkillContext, SkillResult } from '../base_skill.js'

// Generated by the Dev Agent after 2+ CEO rejections landed on the same
// banned-phrase rule — catches it before the CMO->CEO round trip, not after.
const BANNED_PHRASES = [
  'i hope', 'streamline', 'solutions', "in today's", 'boost',
  'take your business to the next level', 'i noticed',
]

export class DraftPrescreen extends BaseSkill {
  static manifest = {
    name: 'draft_prescreen',
    description: 'Flags banned-phrase violations in a CMO draft before it reaches the CEO QA gate',
    version: '1.0.0',
    capabilities: [] as const,
  }

  async execute(input: { subject: string; body: string }): Promise<SkillResult> {
    if (!input?.body) return { ok: false, error: 'expected { subject, body }' }
    const lower = input.body.toLowerCase()
    const hits = BANNED_PHRASES.filter(p => lower.includes(p))
    const questionMarks = (input.body.match(/\\?/g) ?? []).length
    if (questionMarks > 1) hits.push('more than one question mark')
    this.ctx.log(hits.length ? \`prescreen found \${hits.length} violation(s)\` : 'prescreen clean')
    return { ok: true, data: { clean: hits.length === 0, violations: hits } }
  }
}
`,
  domain_reachability_check: `import { BaseSkill, SkillContext, SkillResult } from '../base_skill.js'

// Generated by the Dev Agent after a suppressed/failed send traced back to
// an unreachable domain — protects sender reputation before dispatch.
export class DomainReachabilityCheck extends BaseSkill {
  static manifest = {
    name: 'domain_reachability_check',
    description: 'Confirms a lead\\'s website resolves before it is queued for outreach',
    version: '1.0.0',
    capabilities: ['http_get', 'db_write'] as const,
  }

  async execute(input: { leadId: string; websiteUrl: string }): Promise<SkillResult> {
    if (!input?.websiteUrl) return { ok: false, error: 'expected { leadId, websiteUrl }' }
    try {
      const body = await this.ctx.httpGet!(input.websiteUrl)
      const reachable = body.length > 0
      if (!reachable) {
        this.ctx.dbWrite!(
          \`UPDATE leads SET lead_status='failed', fail_reason='domain_unreachable' WHERE id = ?\`,
          [input.leadId],
        )
      }
      this.ctx.log(\`\${input.websiteUrl}: \${reachable ? 'reachable' : 'unreachable'}\`)
      return { ok: true, data: { reachable } }
    } catch (err) {
      this.ctx.dbWrite!(
        \`UPDATE leads SET lead_status='failed', fail_reason='domain_unreachable' WHERE id = ?\`,
        [input.leadId],
      )
      return { ok: true, data: { reachable: false, error: (err as Error).message } }
    }
  }
}
`,
  lead_enrichment: `import { BaseSkill, SkillContext, SkillResult } from '../base_skill.js'

// Generated by the Dev Agent: no skill yet confirms a prospect's site is
// live before the Researcher spends a cycle auditing it (Part I flags lead
// sourcing/verification as an open decision — this closes the gap cheaply).
export class LeadEnrichment extends BaseSkill {
  static manifest = {
    name: 'lead_enrichment',
    description: 'Verifies a lead\\'s website responds (HTTP 2xx/3xx) before dispatching the Researcher',
    version: '1.0.0',
    capabilities: ['http_get'] as const,
  }

  async execute(input: { websiteUrl: string }): Promise<SkillResult> {
    if (!input?.websiteUrl) return { ok: false, error: 'expected { websiteUrl }' }
    try {
      const body = await this.ctx.httpGet!(input.websiteUrl)
      this.ctx.log(\`fetched \${body.length} bytes from \${input.websiteUrl}\`)
      return { ok: true, data: { live: true, bytes: body.length } }
    } catch (err) {
      return { ok: true, data: { live: false, error: (err as Error).message } }
    }
  }
}
`,
}

export function mockAgent(agentId: string, payload: any): { output: any; inputTokens: number; outputTokens: number } {
  switch (agentId) {
    case 'researcher_agent': {
      const name = payload.company_name as string
      const h = hash(name)
      // ~1 in 11 companies has a genuinely good site -> no flaws -> lead fails out
      const flaws = h % 11 === 0 ? [] : [0, 1, 2].map(i => FLAW_POOL[(h + i * 2) % FLAW_POOL.length])
      return {
        output: {
          company: name, trade: payload.trade,
          flaws, has_online_booking: false, has_ssl: h % 3 !== 0,
          copyright_year: flaws.length ? '2019' : '2026', estimated_last_update: flaws.length ? '2021' : '2026',
        },
        inputTokens: 0, outputTokens: 0, // local model — never counts against anything
      }
    }
    case 'cmo_agent': {
      const audit = payload.audit
      const revised = payload.feedback ? ' (revised)' : ''
      const [f1, f2] = audit.flaws
      const previewLine = payload.preview?.attached
        ? `\n\nWent ahead and mocked up what ${audit.company}'s dispatch screen would look like — picture below, your colors on it.`
        : ''
      return {
        output: {
          subject: `${audit.company} after-hours calls`,
          body: `Quick one${revised} — pulled up the ${audit.company} site from a job board. ${f1.detail}. That's the first place a homeowner with a burst pipe gives up and calls whoever answers. Also: ${f2.detail.toLowerCase()}.${previewLine}\n\nWe build the operational side for ${audit.trade} shops your size — 15 minutes this week to walk through it?`,
        },
        inputTokens: 640, outputTokens: 210,
      }
    }
    case 'ceo_agent': {
      // Every 5th company forces one REJECT round so the QA loop is exercised
      const h = hash(payload.audit.company)
      const firstPass = !payload.draft.body.includes('(revised)')
      if (h % 5 === 0 && firstPass) {
        return {
          output: { approved: false, score: 64, feedback: '1. Opening flaw is stated as tech critique, rephrase as lost revenue. 2. CTA missing a trade-specific reason.' },
          inputTokens: 820, outputTokens: 70,
        }
      }
      return { output: { approved: true, score: 88, feedback: '' }, inputTokens: 820, outputTokens: 12 }
    }
    case 'sales_consult': {
      // Conversion review of an approved draft. Deterministic: drafts that
      // went through a QA revision score lower so the collaboration loop and
      // the dashboard's consult display both get exercised offline.
      const revised = String(payload.draft?.body ?? '').includes('(revised)')
      const h2 = hash(payload.company_name ?? 'x')
      const score = revised ? 62 : 78 + (h2 % 18) // 78–95
      return {
        output: {
          click_score: score,
          notes: score >= 80 ? [] : [
            'Set up the embedded preview earlier — the branded screenshot is the hook, not the audit.',
            `Subject could name the payoff: "${payload.trade ?? 'trade'} calls you’re missing" beats a company-name-only line.`,
          ],
          subject_alt: score >= 80 ? null : `${(payload.trade ?? 'trade')} calls you’re missing`,
        },
        inputTokens: 410, outputTokens: 95,
      }
    }
    case 'sales_rep_agent': {
      // Keyword-driven so the reply pipeline is fully exercisable offline.
      // Mirrors the real prompt's contract exactly (see profiles.json).
      const text = String(payload.reply_text ?? '').toLowerCase()
      const company = payload.company_name ?? 'there'
      const calendar = payload.calendar_link ?? '{{calendar_link}}'
      const has = (...words: string[]) => words.some(w => text.includes(w))

      let out
      if (has('stop', 'unsubscribe', 'remove me', 'take me off', 'do not contact', "don't contact"))
        out = { sentiment: 'unsubscribe', intent: 'removal request', urgency: 1, suggested_reply: null, action: 'suppress' }
      else if (has('out of office', 'auto-reply', 'automatic reply', 'on vacation'))
        out = { sentiment: 'auto_reply', intent: 'automated response', urgency: 1, suggested_reply: null, action: 'ignore' }
      else if (has('interested', 'call', 'sounds good', 'yes', 'let’s talk', "let's talk", 'demo', 'tell me more'))
        out = {
          sentiment: 'positive', intent: 'wants to see it', urgency: 4,
          suggested_reply: `Great — two windows that work on my end: tomorrow 10–10:15am or Thursday 2–2:15pm. Grab whichever suits: ${calendar}. I'll bring the ${company} preview up on screen.`,
          action: 'book_call',
        }
      else if (has('not right now', 'maybe later', 'next quarter', 'busy season', 'circle back'))
        out = {
          sentiment: 'neutral', intent: 'timing objection', urgency: 2,
          suggested_reply: `Understood — busy season is exactly the problem it solves, but timing's yours. I'll check back in a few weeks.`,
          action: 'nurture',
        }
      else
        out = { sentiment: 'negative', intent: 'not interested', urgency: 1, suggested_reply: null, action: 'ignore' }
      return { output: out, inputTokens: 380, outputTokens: 90 }
    }
    case 'analytics_agent': {
      const { day, funnel, ledger, sent } = payload
      const total = Object.values(funnel as Record<string, number>).reduce((a: number, b: any) => a + b, 0)
      const md = [
        `# Daily Digest — ${day}`,
        ``,
        `## Funnel`,
        `| Stage | Count |`,
        `|---|---|`,
        ...Object.entries(funnel).map(([s, n]) => `| ${s} | ${n} |`),
        ``,
        `## Cost`,
        `${ledger.runs} agent runs · ${ledger.tin} in / ${ledger.tout} out tokens · $${Number(ledger.cost).toFixed(4)} (mode never bills per token).`,
        ``,
        `## Deliverability`,
        `${sent} sent today. Opens/replies tracking activates with SEND_MODE=resend webhooks.`,
        ``,
        `## Anomalies`,
        total === 0 ? `No leads in system — seed or import a lead list.` : `None flagged (mock baseline).`,
        ``,
        `## Recommendation`,
        `Approve queued drafts daily; the engine auto-sends on the next cycle.`,
      ].join('\n')
      return { output: md, inputTokens: 480, outputTokens: 290 }
    }
    case 'dev_agent': {
      const { gap } = payload
      const code = DEV_AGENT_TEMPLATES[gap.name]
      if (!code) return { output: `NEEDS_HUMAN — no template for gap "${gap.name}"; capability request needs manual review.`, inputTokens: 900, outputTokens: 60 }
      return { output: code, inputTokens: 1400, outputTokens: 1100 }
    }
    default:
      throw new Error(`No mock for agent ${agentId}`)
  }
}
